S/S/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^smart/', include('smart.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

S/smart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^parsed/$', views.parsed, name='parsed'),
    url(r'^results/$', views.results, name='results'),

    url(r'^parsed_result/$', views.parsed_result, name='parsed_result'),
    url(r'^show/(?P<pk>[a-z\d]+)/$', views.show, name='show'),
]

S/smart/models.py
from __future__ import unicode_literals# -*- coding: utf-8 -*-

from django.db import models

class CV(models.Model):
    name=models.CharField(max_length=250)
    father_name=models.CharField(max_length=250)

S/smart/forms.py
# -*- coding: utf-8 -*-
from django import forms
from splitjson.widgets import SplitJSONWidget


class testForm(forms.Form):
    attrs = {'class': 'form-control input-lg'}
    Results = forms.CharField(widget=SplitJSONWidget(attrs=attrs, debug=False))

S/smart/views.py
from django.db import models
from django.http import HttpResponse
from django.shortcuts import render
import re
from forms import testForm
import os
import json
from pymongo import MongoClient
from django.core.files.storage import FileSystemStorage
import random





def parser(filename):
    os.popen("java -jar Recruit.jar %s" %filename)
    return 0

def index(request):

    return render(request, 'smart/index.html', {'returnedData': ''})

def show(request,pk):
   if pk:
       client = MongoClient()
       db = client['parsed']
       resume = db["resume"]
       pk=int(pk)

       collection=resume.find({"id":pk})
       data=collection[0]
       return render(request, 'smart/show.html', {'returnedData': data})


def results(request):
    client = MongoClient()
    db = client['parsed']
    resume = db["resume"]
    if (('name' in request.GET) and request.GET['name'].strip()) or (('education' in request.GET) and request.GET['education'].strip()) or (('experience' in request.GET) and request.GET['experience'].strip()) or (('skills' in request.GET) and request.GET['skills'].strip()) or (('contact' in request.GET) and request.GET['contact'].strip()):
        name = request.GET['name']
        education = request.GET['education']
        experience = request.GET['experience']
        skills = request.GET['skills']
        contact = request.GET['contact']
        address = request.GET['address']
        category = request.GET['category']
        query_name = "JSON.stringify(this.profile.name).indexOf('"
        query_name += name
        query_name += "')!=-1"

        query_education = "JSON.stringify(this.education).indexOf('"
        query_education += education
        query_education += "')!=-1"

        query_experience = "JSON.stringify(this.experience).indexOf('"
        query_experience += experience
        query_experience += "')!=-1"

        query_skills = "JSON.stringify(this.skills).indexOf('"
        query_skills += skills
        query_skills += "')!=-1"

        query_contact = "JSON.stringify(this.profile.contact_no).indexOf('"
        query_contact += contact
        query_contact += "')!=-1"

        query_address = "JSON.stringify(this.profile.address).indexOf('"
        query_address += address
        query_address += "')!=-1"

        query_category = "JSON.stringify(this.category).indexOf('"
        query_category += category
        query_category += "')!=-1"

        rate=request.GET["sortby"]
        rate=int(rate)
        if rate!=0:
            collection = resume.find({"$or":[{"$where":query_name},{"$where":query_education},
                                             {"$where":query_experience},{"$where":query_skills},
                                             {"$where":query_contact},{"$where":query_address},{"$where":query_category}]}).sort([('ratings',rate)])
            return render(request, 'smart/results.html', {'returnedData': collection})
        else:
            collection = resume.find({"$or": [{"$where": query_name}, {"$where": query_education},
                                              {"$where": query_experience}, {"$where": query_skills},
                                              {"$where": query_contact}, {"$where": query_address},{"$where":query_category}]})
            return render(request, 'smart/results.html', {'returnedData': collection})
    return render(request, 'smart/index.html', {'returnedData': ''})


def parsed(request):
    if os.path.exists('parsed_resume.json'):
        os.remove('parsed_resume.json')
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        name=myfile.name
        name=name.replace(" ","-")
        filename = fs.save(name, myfile)
        uploaded_file_url = fs.url(filename)
        filed = '.'+uploaded_file_url
        parser(filed)
    return render(request,'smart/parsed.html')


def parsed_result(request):
    f = open('parsed_resume.json', "r")
    jsons = json.loads(f.read().decode("utf-8","ignore").lower())
    client = MongoClient()
    db = client['parsed']
    resume=db["resume"]
    form = testForm(request.POST or None, initial={'Results': jsons})

    ratings = request.POST.get('ratings', False)
    category = request.POST.get('category', False)

    location = request.POST.get('location', False)
    website = request.POST.get('website', False)
    phone = request.POST.get('phone', False)
    email = request.POST.get('email', False)

    extra_degree = request.POST.get('extra_degree', False)
    extra_title = request.POST.get('extra_title', False)
    extra_school = request.POST.get('extra_school', False)
    extra_degree_from = request.POST.get('extra_degree_from', False)
    extra_degree_to = request.POST.get('extra_degree_to', False)
    degree_description = request.POST.get('degree_description', False)

    education_external1={"extra_degree":extra_degree,"extra_title":extra_title,"extra_school":extra_school,"extra_degree_from":extra_degree_from,
                         "extra_degree_to":extra_degree_to,"degree_description":degree_description}

    basic={"location":location,"website":website,"phone":phone,"email":email}

    company_name = request.POST.get('company_name', False)
    company_position = request.POST.get('company_position', False)
    start_date = request.POST.get('start_date', False)
    end_date = request.POST.get('end_date', False)
    comments = request.POST.get('comments', False)

    experience_external1 = {"company_name": company_name, "company_position": company_position, "start_date": start_date,
                           "end_date": end_date,
                           "comments": comments}
    if form.is_valid():
        text = form.cleaned_data['Results']
        text = json.loads(text)
        if request.method == 'POST' and request.FILES:
            picture = request.FILES["picture"]
            fs = FileSystemStorage()
            name = picture.name
            name = name.replace(" ", "-")
            filename = fs.save(name, picture)
            uploaded_file_url = fs.url(filename)
            text['image_url'] = uploaded_file_url



        text['ratings']=ratings
        text['category'] = category


        text['basic']=basic
        text['education_external1'] = education_external1
        text['experience_external1'] = experience_external1
        text['id']=random.randint(10000, 210000) * 5

        resume.insert(text,check_keys=False)
        pass
    template = 'smart/parsed_result.html'
    context={'form': form}

    return render(request,template, context)

S/templates/smart/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Post a job position or create your online resume by TheJobs!">
    <meta name="keywords" content="">

    <title>TheJobs - Resume list</title>

    <!-- Styles -->
    <link href="{{ MEDIA_URL }}assets/css/app.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}assets/css/custom.css" rel="stylesheet">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="{{ MEDIA_URL }}assets/img/favicon.ico">
  </head>

  <body class="nav-on-header smart-nav bg-alt">

    <!-- Navigation bar -->
    <nav class="navbar">
      <div class="container">

        <!-- Logo -->
        <div class="pull-left">
          <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

          <div class="logo-wrapper">
            <a class="logo" href="index.html"><img src="{{ MEDIA_URL }}assets/img/logo.png" alt="logo"></a>
            <a class="logo-alt" href="index.html"><img src="{{ MEDIA_URL }}assets/img/logo-alt.png" alt="logo-alt"></a>
          </div>

        </div>
        <!-- END Logo -->

        <!-- User account -->
        
        <!-- END User account -->

        <!-- Navigation menu -->
        <ul class="nav-menu">
          <li>
            <a class="active" href="{% url 'index' %}">Home</a>
            
          </li>
          <li>
            <a href="{% url 'parsed' %}">Parse Resume</a>
            
          </li>
          <li>
            <a href="{% url 'parsed_result' %}">Parsed Results</a>
            
          </li>
          <li>
            <a href="#">Company</a>
            
          </li>
          <li>
            <a href="#">About</a>
            
          </li>
        </ul>
        <!-- END Navigation menu -->

      </div>
    </nav>
    <!-- END Navigation bar -->


    <!-- Page header -->
    <header class="page-header bg-img" style="background-image: url({{ MEDIA_URL }}assets/img/bg-banner1.jpg);">
      <div class="container page-name">
        <h1 class="text-center">Browse resumes</h1>
        <p class="lead text-center">Use following search box to find resumes that fits your position better</p>
      </div>

      <div class="container">
		<form class="" method="get" action="{% url 'results' %}" enctype="multipart/form-data">

          <div class="row">
            <div class="form-group col-xs-12 col-sm-4">
              <input name="name" id="id_name" type="text" class="form-control" placeholder="Name" />
            </div>

            <div class="form-group col-xs-12 col-sm-4">
                  <input name="education" id="id_education" type="text" class="form-control" placeholder="Education" />
            </div>

            <div class="form-group col-xs-12 col-sm-4">
                  <input name="experience" id="id_experience" type="text" class="form-control" placeholder="Experience" />
            </div>

            <div class="form-group col-xs-12 col-sm-4">
                  <input name="skills" id="id_skills" type="text" class="form-control" placeholder="Skills" />
            </div>

			<div class="form-group col-xs-12 col-sm-4">
                  <input name="contact" id="id_contact" type="text" class="form-control" placeholder="Contact No." />
            </div>

            <div class="form-group col-xs-12 col-sm-4">
                  <input name="address" id="id_address" type="text" class="form-control" placeholder="Address" />
            </div>

            <div class="form-group col-xs-12 col-sm-4">
              <select class="form-control selectpicker"  name="category">
                <option selected >All categories</option>
                <option value="developer">Developer</option>
                <option value="designer">Designer</option>
                <option value="customer_service">Customer service</option>
                <option value="finance">Finance</option>
                <option value="healthcare">Healthcare</option>
                <option value="sale">Sale</option>
                <option value="marketing">Marketing</option>
                <option value="information_technology">Information technology</option>
                <option value="others">Others</option>
              </select>
            </div>


            

            


            <div class="form-group col-xs-12 col-sm-4">
              <h6>Sort by</h6>
              <div class="radio">
                <input type="radio" name="sortby" id="sortby1" value="0" checked>
                <label for="sortby1">Relevance</label>
              </div>

              <div class="radio">
                <input type="radio" name="sortby" id="sortby2" value="-1">
                <label for="sortby2">Highest rate first</label>
              </div>

              <div class="radio">
                <input type="radio" name="sortby" id="sortby3" value="1">
                <label for="sortby3">Lowest rate first</label>
              </div>

              

            </div>


          </div>

          <div class="button-group">
            <div class="action-buttons">
              <button class="btn btn-primary">Apply filter</button>
            </div>
          </div>

        </form>

      </div>

    </header>
    <!-- END Page header -->


    <!-- Main container -->
    
    <!-- END Main container -->


   <footer class="site-footer">

      <!-- Top section -->
      
      <!-- END Top section -->

      <!-- Bottom section -->
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyrights &copy; 2017 All Rights Reserved by <a href="#">The Human Resource Consultants</a>.</p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- END Bottom section -->

    </footer>
    <!-- END Site footer -->


    <!-- Back to top button -->
    <a id="scroll-up" href="#"><i class="ti-angle-up"></i></a>
    <!-- END Back to top button -->

    <!-- Scripts -->
    <script src="{{ MEDIA_URL }}assets/js/app.min.js"></script>
    <script src="{{ MEDIA_URL }}assets/vendors/summernote/summernote.min.js"></script>
    <script src="{{ MEDIA_URL }}assets/js/custom.js"></script>

  </body>
</html>

S/templates/smart/parsed.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Post a job position or create your online resume by TheJobs!">
    <meta name="keywords" content="">

    <title>TheJobs - Add resume</title>
    <link href="{{ MEDIA_URL }}assets/css/materialize.min.css" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ MEDIA_URL }}assets/css/app.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}assets/vendors/summernote/summernote.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}assets/css/custom.css" rel="stylesheet">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="{{ MEDIA_URL }}assets/img/favicon.ico">
  </head>

  <body class="nav-on-header smart-nav">

    <!-- Navigation bar -->
    <nav class="navbar">
      <div class="container">

        <!-- Logo -->
        <div class="pull-left">
          <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

          <div class="logo-wrapper">
            <a class="logo" href="index.html"><img src="{{ MEDIA_URL }}assets/img/logo.png" alt="logo"></a>
            <a class="logo-alt" href="index.html"><img src="{{ MEDIA_URL }}assets/img/logo-alt.png" alt="logo-alt"></a>
          </div>

        </div>
        <!-- END Logo -->

        <!-- User account -->
        
        <!-- END User account -->

        <!-- Navigation menu -->
        <ul class="nav-menu">
          <li>
            <a class="active" href="{% url 'index' %}">Home</a>
            
          </li>
          <li>
            <a href="{% url 'parsed' %}">Parse Resume</a>
            
          </li>
          <li>
            <a href="{% url 'parsed_result' %}">Parsed Results</a>
            
          </li>
          <li>
            <a href="#">Company</a>
            
          </li>
          <li>
            <a href="#">About</a>
            
          </li>
        </ul>
        <!-- END Navigation menu -->

      </div>
    </nav>
    <!-- END Navigation bar -->

    <form method="post" enctype="multipart/form-data" id="form">
    {% csrf_token %}

      <!-- Page header -->
      <header class="page-header">
        <div class="container page-name">
          <h1 class="text-center">Extract your resume</h1>
          <p class="lead text-center">Create your resume and put it online.</p>
        </div>

        

          <div class="button-group">
            <div class="action-buttons">

              <div class="upload-button">
                <button class="btn btn-block btn-gray">Choose a resume file</button>
                <input type="file" name="myfile">
              </div>

              <div class="upload-button">
                <button class="dis btn btn-block btn-primary disabled" onclick="window.location.href='{% url 'parsed_result' %}'" type="button">View CV</button>                
              </div>

            </div>


          </div>

        </div>

      </header>

      <p id="message" ></p>
<div class="progress">
      <div class="definite"></div>
  </div>
      <main>

        <section class=" bg-img" style="background-image: url({{ MEDIA_URL }}assets/img/bg-facts.jpg);">
          <div class="container">
            <header class="section-header">
              <span>Are you done?</span>
              <h2>Submit resume</h2>
              
            </header>

            <p class="text-center"><button type="submit" class="btn btn-success btn-xl btn-round">Extractify</button></p>

          </div>
        </section>
        <!-- END Submit -->


      </main>
      <!-- END Main container -->

    </form>

    <!-- Site footer -->
    <footer class="site-footer">

      <!-- Top section -->
      
      <!-- END Top section -->

      <!-- Bottom section -->
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyrights &copy; 2017 All Rights Reserved by <a href="#">The Human Resource Consultants</a>.</p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- END Bottom section -->

    </footer>
    <!-- END Site footer -->


    <!-- Back to top button -->
    <a id="scroll-up" href="#"><i class="ti-angle-up"></i></a>
    <!-- END Back to top button -->

    <!-- Scripts -->

    <script src="{{ MEDIA_URL }}assets/js/jquery-3.1.1.js"></script>
    <script src="{{ MEDIA_URL }}assets/vendors/summernote/summernote.min.js"></script>
    <script src="{{ MEDIA_URL }}assets/js/materialize.min.js"></script> 

    <script src="{{ MEDIA_URL }}assets/js/custom.js"></script> 
    <script>
    function upload(event) {
event.preventDefault();
var data = new FormData($('form').get(0));
$('.definite').addClass('indeterminate');
$("#message").html('<center>You can rectify information once the extraction finishes before submitting it in database</center>');
$.ajax({





	
    url: $(this).attr('action'),
    type: $(this).attr('method'),
    data: data,
    cache: false,
    processData: false,
    contentType: false,

    success: function(data) {
    	$('.definite').removeClass('indeterminate');
    	$('.dis').removeClass('disabled');
        alert('success');
    }
});
return false;
}

$(function() {
    $('form').submit(upload);
});</script>
  </body>
</html>

S/templates/smart/results.html
{% load staticfiles %}
{% load filter %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Post a job position or create your online resume by TheJobs!">
    <meta name="keywords" content="">

    <title>TheJobs - Resume list</title>

    <!-- Styles -->
    <link href="{{ MEDIA_URL }}assets/css/app.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}assets/css/custom.css" rel="stylesheet">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="{{ MEDIA_URL }}assets/img/favicon.ico">
  </head>

  <body class="nav-on-header smart-nav bg-alt">

    <!-- Navigation bar -->
    <nav class="navbar">
      <div class="container">

        <!-- Logo -->
        <div class="pull-left">
          <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

          <div class="logo-wrapper">
            <a class="logo" href="index.html"><img src="{{ MEDIA_URL }}assets/img/logo.png" alt="logo"></a>
            <a class="logo-alt" href="index.html"><img src="{{ MEDIA_URL }}assets/img/logo-alt.png" alt="logo-alt"></a>
          </div>

        </div>
        <!-- END Logo -->

        <!-- User account -->
        
        <!-- END User account -->

        <!-- Navigation menu -->
        <ul class="nav-menu">
          <li>
            <a class="active" href="{% url 'index' %}">Home</a>
            
          </li>
          <li>
            <a href="{% url 'parsed' %}">Parse Resume</a>
            
          </li>
          <li>
            <a href="{% url 'parsed_result' %}">Parsed Results</a>
            
          </li>
          <li>
            <a href="#">Company</a>
            
          </li>
          <li>
            <a href="#">About</a>
            
          </li>
        </ul>
        <!-- END Navigation menu -->

      </div>
    </nav>
    <!-- END Navigation bar -->

    <!-- Page header -->
    <header class="page-header bg-img" style="background-image: url({{ MEDIA_URL }}assets/img/bg-banner1.jpg);">
      


    </header>
    <!-- END Page header -->


    <!-- Main container -->
    <main>
      <section class="no-padding-top bg-alt">
        <div class="container">
          
          {% for doc in returnedData %}
            <!-- Resume detail -->
            <div class="col-sm-12 col-md-6">
              <a class="item-block" href="{% url 'show' doc.id %}">
                <header>
                  {% if doc.image_url %}
                        <img class="resume-avatar" src="{{ doc.image_url}}" alt="">

            {% else %}
                        <img class="resume-avatar" src="{{ MEDIA_URL }}assets/img/avatar-1.jpg" alt="">

            {% endif %}
                 
                  <div class="hgroup">
                    <h4>{{doc.profile.name|title}}</h4>
                  <h5>{{doc.experience.exp.job_title|title}}</h5>
                  </div>
                </header>
    
                <div class="item-body">
                  <p>{{doc.summary.0.objective|title}}</p>

                  
                </div>

                <footer>
                  <ul class="details cols-2">
                    



              <li>
                <i class="fa fa-phone"></i>
                <span>{{doc.profile.contact_no}}</span>
              </li>

              <li>
                <i class="fa fa-envelope"></i>
                {{doc.profile.email}}
              </li>

              <li>
                <i class="fa fa-flag"></i>
                <span>{{doc.profile.nationality}}</span>
              </li>

              <li>
                <i class="fa fa-map-marker"></i>
                <span>{{doc.location}}</span>
              </li>

              <li>
                <i class="fa fa-calendar"></i>
                <span>{{doc.profile.dob}}</span>
              </li>
              
                  </ul>
                </footer>
              </a>
            </div>
            <!-- END Resume detail -->

            {% endfor %}
            


            <!-- END Resume detail -->
          

          


        </div>
        <div class="row"> 
         <div class="container">  
          <!-- Page navigation -->
          <nav class="text-center">
            <ul class="pagination">
              <li>
                <a href="#" aria-label="Previous">
                  <i class="ti-angle-left"></i>
                </a>
              </li>
              <li><a href="#">1</a></li>
              <li class="active"><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li>
                <a href="#" aria-label="Next">
                  <i class="ti-angle-right"></i>
                </a>
              </li>
            </ul>
          </nav>
          <!-- END Page navigation -->
        </div>
</div>
      </section>
    </main>
    <!-- END Main container -->


   <footer class="site-footer">

      <!-- Top section -->
      
      <!-- END Top section -->

      <!-- Bottom section -->
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyrights &copy; 2017 All Rights Reserved by <a href="#">The Human Resource Consultants</a>.</p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- END Bottom section -->

    </footer>
    <!-- END Site footer -->


    <!-- Back to top button -->
    <a id="scroll-up" href="#"><i class="ti-angle-up"></i></a>
    <!-- END Back to top button -->

    <!-- Scripts -->
    <script src="{{ MEDIA_URL }}assets/js/app.min.js"></script>
    <script src="{{ MEDIA_URL }}assets/vendors/summernote/summernote.min.js"></script>
    <script src="{{ MEDIA_URL }}assets/js/custom.js"></script>

  </body>
</html>